export const FETCH_CHANNELS_START = 'FETCH_CHANNELS_START';
export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS';
export const FETCH_CHANNELS_FAIL = 'FETCH_CHANNELS_FAIL';

export const ADD_CHANNEL = 'ADD_CHANNEL';
export const SELECT_CHANNEL = 'SELECT_CHANNEL';
