export const SET_USER = 'SET_USER';

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const NEW_USER = 'NEW_USER';

export const USER_STATUS_CHANGED = 'USER_STATUS_CHANGED';
